# Generated by Django 3.0.2 on 2020-01-04 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyAPI', '0002_auto_20200104_1010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approvals',
            old_name='applicantincome',
            new_name='ApplicantIncome',
        ),
        migrations.RenameField(
            model_name='approvals',
            old_name='coapplicantincome',
            new_name='CoapplicantIncome',
        ),
        migrations.RenameField(
            model_name='approvals',
            old_name='credithistory',
            new_name='Credit_History',
        ),
        migrations.RenameField(
            model_name='approvals',
            old_name='dependants',
            new_name='Dependants',
        ),
        migrations.RenameField(
            model_name='approvals',
            old_name='graduated',
            new_name='Education',
        ),
        migrations.RenameField(
            model_name='approvals',
            old_name='firstname',
            new_name='Firstname',
        ),
        migrations.RenameField(
            model_name='approvals',
            old_name='gender',
            new_name='Gender',
        ),
        migrations.RenameField(
            model_name='approvals',
            old_name='lastname',
            new_name='Lastname',
        ),
        migrations.RenameField(
            model_name='approvals',
            old_name='loanamount',
            new_name='Loan_Amount',
        ),
        migrations.RenameField(
            model_name='approvals',
            old_name='loanterm',
            new_name='Loan_Amount_Term',
        ),
        migrations.RenameField(
            model_name='approvals',
            old_name='married',
            new_name='Married',
        ),
        migrations.RenameField(
            model_name='approvals',
            old_name='area',
            new_name='Property_Area',
        ),
        migrations.RenameField(
            model_name='approvals',
            old_name='selfemployed',
            new_name='Self_Employed',
        ),
    ]
